

#ifndef _RTE_STUB_CALPRM_X_H
#define _RTE_STUB_CALPRM_X_H

#ifdef __cplusplus
extern "C"
{
#endif

ImpTypeValCRdciCorHoldOffTime RTE_Stub_Prm_CRdciCorHoldOffTime(void);
ImpTypeValCRdciDefaultLoadCond RTE_Stub_Prm_CRdciDefaultLoadCond(void);
ImpTypeValCRdciDefaultMenuSel RTE_Stub_Prm_CRdciDefaultMenuSel(void);
ImpTypeValCRdciDeltaPLR RTE_Stub_Prm_CRdciDeltaPLR(void);
ImpTypeValCRdciDispConfTimeout RTE_Stub_Prm_CRdciDispConfTimeout(void);
ImpTypeValCRdciDispReset RTE_Stub_Prm_CRdciDispReset(void);
ImpTypeValCRdciDpToIPmin RTE_Stub_Prm_CRdciDpToIPmin(void);
ImpTypeValCRdciDtAmbPrewarn RTE_Stub_Prm_CRdciDtAmbPrewarn(void);
ImpTypeValCRdciEcoRcpEnable RTE_Stub_Prm_CRdciEcoRcpEnable(void);
ImpTypeValCRdciErfsEnable RTE_Stub_Prm_CRdciErfsEnable(void);
ImpTypeValCRdciErfsPlacardSource RTE_Stub_Prm_CRdciErfsPlacardSource(void);
Rte_CtApHufTpmsSWC_PiCalPrmRDCi_R_Calprm_CRdciErfsReifenEco_FncRetPtrType RTE_Stub_Prm_CRdciErfsReifenEco(void);
ImpTypeValCRdciFastDeflateEnable RTE_Stub_Prm_CRdciFastDeflateEnable(void);
Rte_CtApHufTpmsSWC_PiCalPrmRDCi_R_Calprm_CRdciLearnLocateConfig_FncRetPtrType RTE_Stub_Prm_CRdciLearnLocateConfig(void);
ImpTypeValCRdciLongHoldTime RTE_Stub_Prm_CRdciLongHoldTime(void);
ImpTypeValCRdciMaxCorRcp RTE_Stub_Prm_CRdciMaxCorRcp(void);
ImpTypeValCRdciMaxCorTime RTE_Stub_Prm_CRdciMaxCorTime(void);
ImpTypeValCRdciMaxThreshold RTE_Stub_Prm_CRdciMaxThreshold(void);
ImpTypeValCRdciMinRcpFa RTE_Stub_Prm_CRdciMinRcpFa(void);
ImpTypeValCRdciMinRcpRa RTE_Stub_Prm_CRdciMinRcpRa(void);
ImpTypeValCRdciNumPrewarnDetect RTE_Stub_Prm_CRdciNumPrewarnDetect(void);
ImpTypeValCRdciPInitRangeMax RTE_Stub_Prm_CRdciPInitRangeMax(void);
ImpTypeValCRdciPanneBefPos RTE_Stub_Prm_CRdciPanneBefPos(void);
ImpTypeValCRdciPanneTh RTE_Stub_Prm_CRdciPanneTh(void);
ImpTypeValCRdciPrewarnEnable RTE_Stub_Prm_CRdciPrewarnEnable(void);
ImpTypeValCRdciPrewarnIgnition RTE_Stub_Prm_CRdciPrewarnIgnition(void);
ImpTypeValCRdciResetPlausi RTE_Stub_Prm_CRdciResetPlausi(void);
ImpTypeValCRdciRidEnable RTE_Stub_Prm_CRdciRidEnable(void);
ImpTypeValCRdciSensorForeignAkRdk RTE_Stub_Prm_CRdciSensorForeignAkRdk(void);
ImpTypeValCRdciSensorLocSync RTE_Stub_Prm_CRdciSensorLocSync(void);
ImpTypeValCRdciShortHoldTime RTE_Stub_Prm_CRdciShortHoldTime(void);
ImpTypeValCRdciStatInit RTE_Stub_Prm_CRdciStatInit(void);
ImpTypeValCRdciTPrewarnNc RTE_Stub_Prm_CRdciTPrewarnNc(void);
ImpTypeValCRdciTRefShift RTE_Stub_Prm_CRdciTRefShift(void);
ImpTypeValCRdciThCTol RTE_Stub_Prm_CRdciThCTol(void);
ImpTypeValCRdciThNCTol RTE_Stub_Prm_CRdciThNCTol(void);
ImpTypeValCRdciTimeoutPrewarn RTE_Stub_Prm_CRdciTimeoutPrewarn(void);
ImpTypeValCRdciTpmsMarket RTE_Stub_Prm_CRdciTpmsMarket(void);
Rte_CtApHufTpmsSWC_PiCalPrmRDCi_R_Calprm_CRdciTrefSeasAdjConfig_FncRetPtrType RTE_Stub_Prm_CRdciTrefSeasAdjConfig(void);
ImpTypeValCRdciTrefSeasonalAdjustment RTE_Stub_Prm_CRdciTrefSeasonalAdjustment(void);
ImpTypeValCRdciTyrIdFiltGw RTE_Stub_Prm_CRdciTyrIdFiltGw(void);
ImpTypeValCRdciUiaThC RTE_Stub_Prm_CRdciUiaThC(void);
ImpTypeValCRdciUiaThNc RTE_Stub_Prm_CRdciUiaThNc(void);
ImpTypeValCRdciUiwThC RTE_Stub_Prm_CRdciUiwThC(void);
ImpTypeValCRdciUiwThNc RTE_Stub_Prm_CRdciUiwThNc(void);
ImpTypeValCRdciXminCoolTire RTE_Stub_Prm_CRdciXminCoolTire(void);
ImpTypeVal_C_Funktion_ReifenPannenerkennung_aktiv_e RTE_Stub_Prm_C_Funktion_ReifenPannenerkennung_aktiv_e(void);

ImpTypeValCRdciSpeedCcmEnable RTE_Stub_Prm_CRdciSpeedCcmEnable(void);
ImpTypeValCRdciSpeedCcmHyst RTE_Stub_Prm_CRdciSpeedCcmHyst(void);
ImpTypeValCRdciSpeedCcmPressOffsetFa RTE_Stub_Prm_CRdciSpeedCcmPressOffsetFa(void);
ImpTypeValCRdciSpeedCcmPressOffsetRa RTE_Stub_Prm_CRdciSpeedCcmPressOffsetRa(void);
ImpTypeValCRdciSpeedCcmTh RTE_Stub_Prm_CRdciSpeedCcmTh(void);
ImpTypeValCRdciSpeedCcmTime RTE_Stub_Prm_CRdciSpeedCcmTime(void);

ImpTypeValCRdciParkSupExtParkSupConfig RTE_Stub_Prm_CRdciParkSupExtParkSupConfig(void);
ImpTypeValCRdciParkSupMobilityLossThresholdValue RTE_Stub_Prm_CRdciParkSupMobilityLossThresholdValue(void);
ImpTypeValCRdciParkSupNotificationThresholdValueC RTE_Stub_Prm_CRdciParkSupNotificationThresholdValueC(void);
ImpTypeValCRdciParkSupNotificationThresholdValueNc RTE_Stub_Prm_CRdciParkSupNotificationThresholdValueNc(void);
ImpTypeValCRdciParkSupTolNoTempComp RTE_Stub_Prm_CRdciParkSupTolNoTempComp(void);
ImpTypeValCRdciParkSupTolTempComp RTE_Stub_Prm_CRdciParkSupTolTempComp(void);
ImpTypeValCRdciParkSupWarningThresholdValueC RTE_Stub_Prm_CRdciParkSupWarningThresholdValueC(void);
ImpTypeValCRdciParkSupWarningThresholdValueNc RTE_Stub_Prm_CRdciParkSupWarningThresholdValueNc(void);

#ifdef __cplusplus
}
#endif

#endif
